service: neurotech-api
configValidationMode: error

layers:
  neurotech:
    path: ../build/neurotech
    name: ${opt:stage}-neurotech-layer
    description: Neurotech service lib
    compatibleRuntimes:
      - python3.8

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  deploymentBucket:
    name: ${self:service}-${opt:stage}-deploy


package:
  exclude:
      - Makefile
      - README.md
      - test/**
      - .serverless/**

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: serverless-fastapi-deps
      description: Dependencies of serverless-fastapi
      compatibleRuntimes:
        - python3.8

functions:
  api:
    handler: app.main.handler
    layers:
      - { Ref: NeurotechLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}